/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package HomeGenius;


/**
 *
 * @author lani
 */
public class EditRecipe extends javax.swing.JFrame {

    /**
     * Creates new form HomeGeniusPanel
     */
    public EditRecipe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PurpleLayout = new javax.swing.JPanel();
        GreyLayout = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        addImage = new javax.swing.JButton();
        ingredients = new javax.swing.JLabel();
        ingredients1 = new javax.swing.JLabel();
        ingredients2 = new javax.swing.JLabel();
        ingredients3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        ingredientList = new javax.swing.JPanel();
        instructions = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        instructions1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        instructions2 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        instructions3 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        instructions4 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        ingredientList1 = new javax.swing.JPanel();
        ingredients4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        saveButt = new javax.swing.JButton();
        Home = new javax.swing.JLabel();
        Genius = new javax.swing.JLabel();
        HouseIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PurpleLayout.setBackground(new java.awt.Color(204, 204, 255));
        PurpleLayout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GreyLayout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("Edit recipe");
        GreyLayout.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));
        GreyLayout.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 43, 880, 10));

        addImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ApplePie140x120.png"))); // NOI18N
        addImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addImageActionPerformed(evt);
            }
        });
        GreyLayout.add(addImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 140, 120));

        ingredients.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ingredients.setForeground(new java.awt.Color(102, 102, 255));
        ingredients.setText("Steps:");
        GreyLayout.add(ingredients, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, -1));

        ingredients1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ingredients1.setForeground(new java.awt.Color(102, 102, 255));
        ingredients1.setText("Name:");
        GreyLayout.add(ingredients1, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 70, -1, -1));

        ingredients2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ingredients2.setForeground(new java.awt.Color(102, 102, 255));
        ingredients2.setText("Cooking time:");
        GreyLayout.add(ingredients2, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 110, -1, -1));

        ingredients3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ingredients3.setForeground(new java.awt.Color(102, 102, 255));
        ingredients3.setText("Ingredients:");
        GreyLayout.add(ingredients3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(51, 51, 51));
        jTextField1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        GreyLayout.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 250, -1));

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(51, 51, 51));
        jTextField2.setText("Apple Pie Oats");
        jTextField2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        GreyLayout.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 75, 250, -1));

        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(51, 51, 51));
        jTextField3.setText("10 minutes");
        jTextField3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        GreyLayout.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 115, 250, -1));

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        GreyLayout.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 40, 90));

        jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        GreyLayout.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 75, 250, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(51, 51, 51));
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setViewportView(jTextArea1);

        GreyLayout.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 250, 90));

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setText("+");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        GreyLayout.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, -1, 22));

        jButton30.setBackground(new java.awt.Color(102, 102, 255));
        jButton30.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton30.setForeground(new java.awt.Color(255, 255, 255));
        jButton30.setText("Save");
        jButton30.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        GreyLayout.add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 60, 90, 30));

        ingredientList.setBackground(new java.awt.Color(204, 204, 255));
        ingredientList.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        instructions.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        instructions.setForeground(new java.awt.Color(102, 102, 255));
        instructions.setText("Step 4:");
        ingredientList.add(instructions, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, -1));

        jSeparator5.setForeground(new java.awt.Color(153, 153, 153));
        ingredientList.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 660, 10));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 255));
        jLabel18.setText("Step 1:");
        ingredientList.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 292, -1, -1));

        instructions1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        instructions1.setForeground(new java.awt.Color(102, 102, 255));
        instructions1.setText("Instructions");
        ingredientList.add(instructions1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 10, -1, -1));

        jScrollPane4.setBackground(new java.awt.Color(204, 204, 255));
        jScrollPane4.setBorder(null);
        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextArea4.setBackground(new java.awt.Color(204, 204, 255));
        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextArea4.setForeground(new java.awt.Color(51, 51, 51));
        jTextArea4.setRows(5);
        jTextArea4.setText("Pile hot oats into a bowl, top with caramelised \napples and your choice of toppings and enjoy!");
        jScrollPane4.setViewportView(jTextArea4);

        ingredientList.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 270, 40));

        instructions2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        instructions2.setForeground(new java.awt.Color(102, 102, 255));
        instructions2.setText("Step 1:");
        ingredientList.add(instructions2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jScrollPane5.setBackground(new java.awt.Color(204, 204, 255));
        jScrollPane5.setBorder(null);
        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextArea5.setBackground(new java.awt.Color(204, 204, 255));
        jTextArea5.setColumns(20);
        jTextArea5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextArea5.setForeground(new java.awt.Color(51, 51, 51));
        jTextArea5.setRows(5);
        jTextArea5.setText("Place oats, water, cinnamon and nutmeg\nin a saucepan.");
        jScrollPane5.setViewportView(jTextArea5);

        ingredientList.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 38, 260, 40));

        instructions3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        instructions3.setForeground(new java.awt.Color(102, 102, 255));
        instructions3.setText("Step 2:");
        ingredientList.add(instructions3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jScrollPane6.setBackground(new java.awt.Color(204, 204, 255));
        jScrollPane6.setBorder(null);
        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextArea6.setBackground(new java.awt.Color(204, 204, 255));
        jTextArea6.setColumns(20);
        jTextArea6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextArea6.setForeground(new java.awt.Color(51, 51, 51));
        jTextArea6.setRows(5);
        jTextArea6.setText("Dice 1/2 the apple into small cubes and place \nin the saucepan with the oats. \nBring to a boil and stir until the oats are creamy \nand the apple pieces are tender.\nAbout 4 – 5 minutes. \nAdd a dash more water if necessary.");
        jScrollPane6.setViewportView(jTextArea6);

        ingredientList.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 88, 260, 40));

        instructions4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        instructions4.setForeground(new java.awt.Color(102, 102, 255));
        instructions4.setText("Step 3:");
        ingredientList.add(instructions4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, -1, -1));

        jScrollPane7.setBackground(new java.awt.Color(204, 204, 255));
        jScrollPane7.setBorder(null);
        jScrollPane7.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextArea7.setBackground(new java.awt.Color(204, 204, 255));
        jTextArea7.setColumns(20);
        jTextArea7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextArea7.setForeground(new java.awt.Color(51, 51, 51));
        jTextArea7.setRows(5);
        jTextArea7.setText("Dice remaining apple and place in a frying pan\nwith coconut oil, 2 tbsp water and 1 tsp \ncoconut sugar and saute until apples are \ntender and caramelised.");
        jScrollPane7.setViewportView(jTextArea7);

        ingredientList.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 270, 40));

        jButton4.setBackground(new java.awt.Color(204, 204, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/14x14editt.png"))); // NOI18N
        jButton4.setBorder(null);
        ingredientList.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jButton6.setBackground(new java.awt.Color(204, 204, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/14x14editt.png"))); // NOI18N
        jButton6.setBorder(null);
        ingredientList.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jButton7.setBackground(new java.awt.Color(204, 204, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/14x14editt.png"))); // NOI18N
        jButton7.setBorder(null);
        ingredientList.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, -1, -1));

        jButton8.setBackground(new java.awt.Color(204, 204, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/14x14editt.png"))); // NOI18N
        jButton8.setBorder(null);
        ingredientList.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, -1, -1));

        GreyLayout.add(ingredientList, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 680, 140));

        ingredientList1.setBackground(new java.awt.Color(204, 204, 255));
        ingredientList1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ingredients4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ingredients4.setForeground(new java.awt.Color(102, 102, 255));
        ingredients4.setText("Ingredients");
        ingredientList1.add(ingredients4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 6, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(123, 123, 187));
        ingredientList1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 28, 150, 10));

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextArea2.setBackground(new java.awt.Color(204, 204, 255));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(51, 51, 51));
        jTextArea2.setRows(5);
        jTextArea2.setText("1/2 cup rolled oats\n1 1/4 cups water\n1/2 tsp ground cinnamon\n1/2 tsp ground nutmeg\n1 small apple, diced\n1 tbsp coconut oil\n1 tsp coconut sugar\n\n\n\n\n\n");
        jScrollPane2.setViewportView(jTextArea2);

        ingredientList1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 40, 160, 190));

        jButton3.setBackground(new java.awt.Color(204, 204, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/14x14editt.png"))); // NOI18N
        jButton3.setBorder(null);
        ingredientList1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 8, 16, 14));

        GreyLayout.add(ingredientList1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 170, 240));

        jButton5.setBackground(new java.awt.Color(242, 242, 242));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/14x14editt.png"))); // NOI18N
        jButton5.setBorder(null);
        GreyLayout.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 16, 14));

        saveButt.setBackground(new java.awt.Color(204, 204, 255));
        saveButt.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        saveButt.setForeground(new java.awt.Color(102, 102, 255));
        saveButt.setText("Back");
        saveButt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        saveButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtActionPerformed(evt);
            }
        });
        GreyLayout.add(saveButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 90, 25));

        PurpleLayout.add(GreyLayout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 900, 460));

        Home.setFont(new java.awt.Font("Roboto Slab", 1, 18)); // NOI18N
        Home.setForeground(new java.awt.Color(123, 123, 187));
        Home.setText("Home");
        PurpleLayout.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 5, -1, 38));

        Genius.setFont(new java.awt.Font("Roboto Slab", 1, 18)); // NOI18N
        Genius.setForeground(new java.awt.Color(123, 123, 187));
        Genius.setText("Genius");
        PurpleLayout.add(Genius, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 25, -1, 30));

        HouseIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HomeButton.png"))); // NOI18N
        PurpleLayout.add(HouseIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PurpleLayout, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PurpleLayout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void addImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addImageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addImageActionPerformed

    private void saveButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtActionPerformed
        // TODO add your handling code here:

        // add code for error if not all text fields/ name have no input "Error saving recipe"

      

    }//GEN-LAST:event_saveButtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditRecipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditRecipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditRecipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditRecipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditRecipe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Genius;
    private javax.swing.JPanel GreyLayout;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel HouseIcon;
    private javax.swing.JPanel PurpleLayout;
    private javax.swing.JButton addImage;
    private javax.swing.JPanel ingredientList;
    private javax.swing.JPanel ingredientList1;
    private javax.swing.JLabel ingredients;
    private javax.swing.JLabel ingredients1;
    private javax.swing.JLabel ingredients2;
    private javax.swing.JLabel ingredients3;
    private javax.swing.JLabel ingredients4;
    private javax.swing.JLabel instructions;
    private javax.swing.JLabel instructions1;
    private javax.swing.JLabel instructions2;
    private javax.swing.JLabel instructions3;
    private javax.swing.JLabel instructions4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton saveButt;
    // End of variables declaration//GEN-END:variables
}


