/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package HomeGenius;

/**
 *
 * @author lani
 */
public class HomeGeniusPanel extends javax.swing.JFrame {

    /**
     * Creates new form HomeGeniusPanel
     */
    public HomeGeniusPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PurpleLayout = new javax.swing.JPanel();
        GreyLayout = new javax.swing.JPanel();
        Home = new javax.swing.JLabel();
        Genius = new javax.swing.JLabel();
        HouseIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PurpleLayout.setBackground(new java.awt.Color(204, 204, 255));
        PurpleLayout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GreyLayout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PurpleLayout.add(GreyLayout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 900, 460));

        Home.setFont(new java.awt.Font("Roboto Slab", 1, 18)); // NOI18N
        Home.setForeground(new java.awt.Color(123, 123, 187));
        Home.setText("Home");
        PurpleLayout.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 5, -1, 38));

        Genius.setFont(new java.awt.Font("Roboto Slab", 1, 18)); // NOI18N
        Genius.setForeground(new java.awt.Color(123, 123, 187));
        Genius.setText("Genius");
        PurpleLayout.add(Genius, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 25, -1, 30));

        HouseIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HomeButton.png"))); // NOI18N
        PurpleLayout.add(HouseIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PurpleLayout, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PurpleLayout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeGeniusPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeGeniusPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeGeniusPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeGeniusPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeGeniusPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Genius;
    private javax.swing.JPanel GreyLayout;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel HouseIcon;
    private javax.swing.JPanel PurpleLayout;
    // End of variables declaration//GEN-END:variables
}


