/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package HomeGenius;

/**
 *
 * @author lani
 */
public class RecipeBook1 extends javax.swing.JFrame {

    /**
     * Creates new form HomeGeniusPanel
     */
    public RecipeBook1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PurpleLayout = new javax.swing.JPanel();
        GreyLayout = new javax.swing.JPanel();
        recipeBook = new javax.swing.JLabel();
        separatorMain = new javax.swing.JSeparator();
        z = new javax.swing.JButton();
        a = new javax.swing.JButton();
        b = new javax.swing.JButton();
        c = new javax.swing.JButton();
        d = new javax.swing.JButton();
        e = new javax.swing.JButton();
        f = new javax.swing.JButton();
        g = new javax.swing.JButton();
        h = new javax.swing.JButton();
        i = new javax.swing.JButton();
        j = new javax.swing.JButton();
        k = new javax.swing.JButton();
        l = new javax.swing.JButton();
        m = new javax.swing.JButton();
        n = new javax.swing.JButton();
        o = new javax.swing.JButton();
        p = new javax.swing.JButton();
        q = new javax.swing.JButton();
        r = new javax.swing.JButton();
        s = new javax.swing.JButton();
        t = new javax.swing.JButton();
        u = new javax.swing.JButton();
        v = new javax.swing.JButton();
        w = new javax.swing.JButton();
        x = new javax.swing.JButton();
        y = new javax.swing.JButton();
        image2 = new javax.swing.JLabel();
        image1 = new javax.swing.JLabel();
        recipeName2 = new javax.swing.JLabel();
        recipeName1 = new javax.swing.JLabel();
        description1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        description2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        addRecipeButt = new javax.swing.JButton();
        view2Butt = new javax.swing.JButton();
        view1Butt = new javax.swing.JButton();
        separator2 = new javax.swing.JSeparator();
        saveButt = new javax.swing.JButton();
        Home = new javax.swing.JLabel();
        Genius = new javax.swing.JLabel();
        HouseIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PurpleLayout.setBackground(new java.awt.Color(204, 204, 255));
        PurpleLayout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GreyLayout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        recipeBook.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        recipeBook.setForeground(new java.awt.Color(102, 102, 255));
        recipeBook.setText("Recipe Book");
        GreyLayout.add(recipeBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        separatorMain.setForeground(new java.awt.Color(153, 153, 153));
        GreyLayout.add(separatorMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 43, 880, 10));

        z.setBackground(new java.awt.Color(242, 242, 242));
        z.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        z.setForeground(new java.awt.Color(102, 102, 255));
        z.setText("Z");
        z.setBorder(null);
        GreyLayout.add(z, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 60, -1, -1));

        a.setBackground(new java.awt.Color(242, 242, 242));
        a.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        a.setForeground(new java.awt.Color(102, 102, 255));
        a.setText("A");
        a.setBorder(null);
        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });
        GreyLayout.add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        b.setBackground(new java.awt.Color(242, 242, 242));
        b.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b.setForeground(new java.awt.Color(102, 102, 255));
        b.setText("B");
        b.setBorder(null);
        GreyLayout.add(b, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        c.setBackground(new java.awt.Color(242, 242, 242));
        c.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        c.setForeground(new java.awt.Color(102, 102, 255));
        c.setText("C");
        c.setBorder(null);
        GreyLayout.add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        d.setBackground(new java.awt.Color(242, 242, 242));
        d.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        d.setForeground(new java.awt.Color(102, 102, 255));
        d.setText("D");
        d.setBorder(null);
        GreyLayout.add(d, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        e.setBackground(new java.awt.Color(242, 242, 242));
        e.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        e.setForeground(new java.awt.Color(102, 102, 255));
        e.setText("E");
        e.setBorder(null);
        GreyLayout.add(e, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        f.setBackground(new java.awt.Color(242, 242, 242));
        f.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        f.setForeground(new java.awt.Color(102, 102, 255));
        f.setText("F");
        f.setBorder(null);
        GreyLayout.add(f, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));

        g.setBackground(new java.awt.Color(242, 242, 242));
        g.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        g.setForeground(new java.awt.Color(102, 102, 255));
        g.setText("G");
        g.setBorder(null);
        GreyLayout.add(g, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        h.setBackground(new java.awt.Color(242, 242, 242));
        h.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        h.setForeground(new java.awt.Color(102, 102, 255));
        h.setText("H");
        h.setBorder(null);
        GreyLayout.add(h, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        i.setBackground(new java.awt.Color(242, 242, 242));
        i.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        i.setForeground(new java.awt.Color(102, 102, 255));
        i.setText("I");
        i.setBorder(null);
        GreyLayout.add(i, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, -1));

        j.setBackground(new java.awt.Color(242, 242, 242));
        j.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        j.setForeground(new java.awt.Color(102, 102, 255));
        j.setText("J");
        j.setBorder(null);
        GreyLayout.add(j, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        k.setBackground(new java.awt.Color(242, 242, 242));
        k.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        k.setForeground(new java.awt.Color(102, 102, 255));
        k.setText("K");
        k.setBorder(null);
        GreyLayout.add(k, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, -1));

        l.setBackground(new java.awt.Color(242, 242, 242));
        l.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        l.setForeground(new java.awt.Color(102, 102, 255));
        l.setText("L");
        l.setBorder(null);
        GreyLayout.add(l, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, -1, -1));

        m.setBackground(new java.awt.Color(242, 242, 242));
        m.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        m.setForeground(new java.awt.Color(102, 102, 255));
        m.setText("M");
        m.setBorder(null);
        GreyLayout.add(m, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, -1, -1));

        n.setBackground(new java.awt.Color(242, 242, 242));
        n.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        n.setForeground(new java.awt.Color(102, 102, 255));
        n.setText("N");
        n.setBorder(null);
        GreyLayout.add(n, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, -1, -1));

        o.setBackground(new java.awt.Color(242, 242, 242));
        o.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        o.setForeground(new java.awt.Color(102, 102, 255));
        o.setText("O");
        o.setBorder(null);
        GreyLayout.add(o, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, -1, -1));

        p.setBackground(new java.awt.Color(242, 242, 242));
        p.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        p.setForeground(new java.awt.Color(102, 102, 255));
        p.setText("P");
        p.setBorder(null);
        GreyLayout.add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, -1, -1));

        q.setBackground(new java.awt.Color(242, 242, 242));
        q.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        q.setForeground(new java.awt.Color(102, 102, 255));
        q.setText("Q");
        q.setBorder(null);
        GreyLayout.add(q, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, -1, -1));

        r.setBackground(new java.awt.Color(242, 242, 242));
        r.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        r.setForeground(new java.awt.Color(102, 102, 255));
        r.setText("R");
        r.setBorder(null);
        GreyLayout.add(r, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, -1, -1));

        s.setBackground(new java.awt.Color(242, 242, 242));
        s.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        s.setForeground(new java.awt.Color(102, 102, 255));
        s.setText("S");
        s.setBorder(null);
        GreyLayout.add(s, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, -1, -1));

        t.setBackground(new java.awt.Color(242, 242, 242));
        t.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        t.setForeground(new java.awt.Color(102, 102, 255));
        t.setText("T");
        t.setBorder(null);
        GreyLayout.add(t, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, -1, -1));

        u.setBackground(new java.awt.Color(242, 242, 242));
        u.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        u.setForeground(new java.awt.Color(102, 102, 255));
        u.setText("U");
        u.setBorder(null);
        GreyLayout.add(u, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 60, -1, -1));

        v.setBackground(new java.awt.Color(242, 242, 242));
        v.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        v.setForeground(new java.awt.Color(102, 102, 255));
        v.setText("V");
        v.setBorder(null);
        GreyLayout.add(v, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, -1, -1));

        w.setBackground(new java.awt.Color(242, 242, 242));
        w.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        w.setForeground(new java.awt.Color(102, 102, 255));
        w.setText("W");
        w.setBorder(null);
        GreyLayout.add(w, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 60, -1, -1));

        x.setBackground(new java.awt.Color(242, 242, 242));
        x.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        x.setForeground(new java.awt.Color(102, 102, 255));
        x.setText("X");
        x.setBorder(null);
        GreyLayout.add(x, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 60, -1, -1));

        y.setBackground(new java.awt.Color(242, 242, 242));
        y.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        y.setForeground(new java.awt.Color(102, 102, 255));
        y.setText("Y");
        y.setBorder(null);
        GreyLayout.add(y, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 60, -1, -1));

        image2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/90x90.png"))); // NOI18N
        image2.setToolTipText("");
        GreyLayout.add(image2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 90, 90));

        image1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Apple90.png"))); // NOI18N
        image1.setToolTipText("");
        GreyLayout.add(image1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 90, 90));

        recipeName2.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        recipeName2.setForeground(new java.awt.Color(102, 102, 255));
        recipeName2.setText("Aglio e Olio e peperoncino");
        GreyLayout.add(recipeName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        recipeName1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        recipeName1.setForeground(new java.awt.Color(102, 102, 255));
        recipeName1.setText("Apple Pie Oats");
        GreyLayout.add(recipeName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        description1.setBorder(null);
        description1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        description1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setBackground(new java.awt.Color(242, 242, 242));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Breakfast that tastes like dessert, that is \nalso gluten-free and nutrtitious!");
        jTextArea1.setBorder(null);
        description1.setViewportView(jTextArea1);

        GreyLayout.add(description1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 145, 270, 50));

        description2.setBorder(null);
        description2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        description2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea2.setBackground(new java.awt.Color(242, 242, 242));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("An italian classic - easy to make with\njust 4 ingredients and it always is a winner!");
        jTextArea2.setBorder(null);
        description2.setViewportView(jTextArea2);

        GreyLayout.add(description2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 265, 270, 50));

        addRecipeButt.setBackground(new java.awt.Color(102, 102, 255));
        addRecipeButt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addRecipeButt.setForeground(new java.awt.Color(255, 255, 255));
        addRecipeButt.setText("Add recipe");
        addRecipeButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRecipeButtActionPerformed(evt);
            }
        });
        GreyLayout.add(addRecipeButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 13, 105, 25));

        view2Butt.setBackground(new java.awt.Color(204, 204, 255));
        view2Butt.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        view2Butt.setForeground(new java.awt.Color(102, 102, 255));
        view2Butt.setText("View");
        view2Butt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        view2Butt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view2ButtActionPerformed(evt);
            }
        });
        GreyLayout.add(view2Butt, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 250, 90, 30));

        view1Butt.setBackground(new java.awt.Color(204, 204, 255));
        view1Butt.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        view1Butt.setForeground(new java.awt.Color(102, 102, 255));
        view1Butt.setText("View");
        view1Butt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        view1Butt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view1ButtActionPerformed(evt);
            }
        });
        GreyLayout.add(view1Butt, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 140, 90, 30));

        separator2.setForeground(new java.awt.Color(204, 204, 204));
        GreyLayout.add(separator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 880, 10));

        saveButt.setBackground(new java.awt.Color(204, 204, 255));
        saveButt.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        saveButt.setForeground(new java.awt.Color(102, 102, 255));
        saveButt.setText("Back");
        saveButt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        saveButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtActionPerformed(evt);
            }
        });
        GreyLayout.add(saveButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 90, 25));

        PurpleLayout.add(GreyLayout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 900, 460));

        Home.setFont(new java.awt.Font("Roboto Slab", 1, 18)); // NOI18N
        Home.setForeground(new java.awt.Color(123, 123, 187));
        Home.setText("Home");
        PurpleLayout.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 5, -1, 38));

        Genius.setFont(new java.awt.Font("Roboto Slab", 1, 18)); // NOI18N
        Genius.setForeground(new java.awt.Color(123, 123, 187));
        Genius.setText("Genius");
        PurpleLayout.add(Genius, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 25, -1, 30));

        HouseIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HomeButton.png"))); // NOI18N
        PurpleLayout.add(HouseIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PurpleLayout, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PurpleLayout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addRecipeButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRecipeButtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addRecipeButtActionPerformed

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aActionPerformed

    private void view1ButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view1ButtActionPerformed
        // TODO add your handling code here:
        ViewRecipe viewRecipe = new ViewRecipe();
        viewRecipe.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_view1ButtActionPerformed

    private void view2ButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view2ButtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_view2ButtActionPerformed

    private void saveButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtActionPerformed
        // TODO add your handling code here:

        // add code for error if not all text fields/ name have no input "Error saving recipe"

       

    }//GEN-LAST:event_saveButtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecipeBook1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecipeBook1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecipeBook1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecipeBook1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecipeBook1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Genius;
    private javax.swing.JPanel GreyLayout;
    private javax.swing.JPanel GreyLayout1;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel HouseIcon;
    private javax.swing.JPanel PurpleLayout;
    private javax.swing.JPanel PurpleLayout1;
    private javax.swing.JButton a;
    private javax.swing.JButton addImage;
    private javax.swing.JLabel addRecipe;
    private javax.swing.JButton addRecipeButt;
    private javax.swing.JButton b;
    private javax.swing.JButton c;
    private javax.swing.JButton d;
    private javax.swing.JScrollPane description1;
    private javax.swing.JScrollPane description2;
    private javax.swing.JButton e;
    private javax.swing.JButton f;
    private javax.swing.JButton g;
    private javax.swing.JButton h;
    private javax.swing.JButton i;
    private javax.swing.JLabel image1;
    private javax.swing.JLabel image2;
    private javax.swing.JButton j;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JButton k;
    private javax.swing.JButton l;
    private javax.swing.JButton m;
    private javax.swing.JButton n;
    private javax.swing.JButton o;
    private javax.swing.JButton p;
    private javax.swing.JButton q;
    private javax.swing.JButton r;
    private javax.swing.JLabel recipeBook;
    private javax.swing.JLabel recipeName1;
    private javax.swing.JLabel recipeName2;
    private javax.swing.JButton s;
    private javax.swing.JButton saveButt;
    private javax.swing.JSeparator separator2;
    private javax.swing.JSeparator separatorMain;
    private javax.swing.JSeparator separatorMain1;
    private javax.swing.JButton t;
    private javax.swing.JButton u;
    private javax.swing.JButton v;
    private javax.swing.JButton view1Butt;
    private javax.swing.JButton view2Butt;
    private javax.swing.JButton w;
    private javax.swing.JButton x;
    private javax.swing.JButton y;
    private javax.swing.JButton z;
    // End of variables declaration//GEN-END:variables
}


