/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package HomeGenius;

/**
 *
 * @author lani
 */
public class ViewRecipe extends javax.swing.JFrame {

    /**
     * Creates new form HomeGeniusPanel
     */
    public ViewRecipe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PurpleLayout = new javax.swing.JPanel();
        GreyLayout = new javax.swing.JPanel();
        recipeName = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        ingredientList = new javax.swing.JPanel();
        ingredients = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        addToShoppingList = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        separatorMain = new javax.swing.JSeparator();
        step4 = new javax.swing.JLabel();
        instructions = new javax.swing.JLabel();
        step1 = new javax.swing.JLabel();
        step2 = new javax.swing.JLabel();
        step3 = new javax.swing.JLabel();
        descStep4 = new javax.swing.JScrollPane();
        descStep4Text = new javax.swing.JTextArea();
        descStep1 = new javax.swing.JScrollPane();
        descStep1Text = new javax.swing.JTextArea();
        descStep3 = new javax.swing.JScrollPane();
        descStep3Text = new javax.swing.JTextArea();
        instSeparator1 = new javax.swing.JSeparator();
        instSeparator2 = new javax.swing.JSeparator();
        descStep2 = new javax.swing.JScrollPane();
        descStep2Text = new javax.swing.JTextArea();
        editButt = new javax.swing.JButton();
        saveButt = new javax.swing.JButton();
        Home = new javax.swing.JLabel();
        Genius = new javax.swing.JLabel();
        HouseIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PurpleLayout.setBackground(new java.awt.Color(204, 204, 255));
        PurpleLayout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GreyLayout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        recipeName.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        recipeName.setForeground(new java.awt.Color(102, 102, 255));
        recipeName.setText("Apple Pie Oats");
        GreyLayout.add(recipeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/180220.png"))); // NOI18N
        GreyLayout.add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 220, 180));

        ingredientList.setBackground(new java.awt.Color(204, 204, 255));
        ingredientList.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ingredients.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ingredients.setForeground(new java.awt.Color(102, 102, 255));
        ingredients.setText("Ingredients");
        ingredientList.add(ingredients, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 6, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(123, 123, 187));
        ingredientList.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 34, 480, 10));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Optional toppings:");
        ingredientList.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 39, -1, -1));

        addToShoppingList.setBackground(new java.awt.Color(102, 102, 255));
        addToShoppingList.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        addToShoppingList.setForeground(new java.awt.Color(255, 255, 255));
        addToShoppingList.setText("Add to shopping list");
        ingredientList.add(addToShoppingList, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 7, -1, -1));

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextArea2.setBackground(new java.awt.Color(204, 204, 255));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(51, 51, 51));
        jTextArea2.setRows(5);
        jTextArea2.setText("1/2 cup rolled oats\n1 1/4 cups water\n1/2 tsp ground cinnamon\n1/2 tsp ground nutmeg\n1 small apple, diced\n1 tbsp coconut oil\n1 tsp coconut sugar\n\n");
        jScrollPane2.setViewportView(jTextArea2);

        ingredientList.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 200, 130));

        jScrollPane6.setBackground(new java.awt.Color(204, 204, 255));
        jScrollPane6.setBorder(null);
        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextArea6.setBackground(new java.awt.Color(204, 204, 255));
        jTextArea6.setColumns(20);
        jTextArea6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea6.setForeground(new java.awt.Color(51, 51, 51));
        jTextArea6.setRows(5);
        jTextArea6.setText("1 tbsp plain yoghurt\n1 tbsp nut butter of choice");
        jScrollPane6.setViewportView(jTextArea6);

        ingredientList.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 260, -1));

        GreyLayout.add(ingredientList, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 500, 180));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Cooking time: 10 minutes");
        GreyLayout.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 13, -1, -1));

        separatorMain.setForeground(new java.awt.Color(153, 153, 153));
        GreyLayout.add(separatorMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 43, 880, 10));

        step4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        step4.setForeground(new java.awt.Color(102, 102, 255));
        step4.setText("Step 4:");
        GreyLayout.add(step4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, -1, -1));

        instructions.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        instructions.setForeground(new java.awt.Color(102, 102, 255));
        instructions.setText("Instructions");
        GreyLayout.add(instructions, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        step1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        step1.setForeground(new java.awt.Color(102, 102, 255));
        step1.setText("Step 1:");
        GreyLayout.add(step1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 292, -1, -1));

        step2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        step2.setForeground(new java.awt.Color(102, 102, 255));
        step2.setText("Step 2:");
        GreyLayout.add(step2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        step3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        step3.setForeground(new java.awt.Color(102, 102, 255));
        step3.setText("Step 3:");
        GreyLayout.add(step3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, -1, -1));

        descStep4.setBackground(new java.awt.Color(232, 232, 232));
        descStep4.setBorder(null);
        descStep4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        descStep4Text.setBackground(new java.awt.Color(242, 242, 242));
        descStep4Text.setColumns(20);
        descStep4Text.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        descStep4Text.setForeground(new java.awt.Color(51, 51, 51));
        descStep4Text.setRows(5);
        descStep4Text.setText("Pile hot oats into a bowl, top with caramelised \napples and your choice of toppings and enjoy!");
        descStep4.setViewportView(descStep4Text);

        GreyLayout.add(descStep4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 350, 50));

        descStep1.setBackground(new java.awt.Color(232, 232, 232));
        descStep1.setBorder(null);
        descStep1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        descStep1Text.setBackground(new java.awt.Color(242, 242, 242));
        descStep1Text.setColumns(20);
        descStep1Text.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        descStep1Text.setForeground(new java.awt.Color(51, 51, 51));
        descStep1Text.setRows(5);
        descStep1Text.setText("Place oats, water, cinnamon and nutmeg\nin a saucepan.");
        descStep1.setViewportView(descStep1Text);

        GreyLayout.add(descStep1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 370, 50));

        descStep3.setBackground(new java.awt.Color(232, 232, 232));
        descStep3.setBorder(null);
        descStep3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        descStep3Text.setBackground(new java.awt.Color(242, 242, 242));
        descStep3Text.setColumns(20);
        descStep3Text.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        descStep3Text.setForeground(new java.awt.Color(51, 51, 51));
        descStep3Text.setRows(5);
        descStep3Text.setText("Dice remaining apple and place in a frying pan\nwith coconut oil, 2 tbsp water and 1 tsp \ncoconut sugar and saute until apples are \ntender and caramelised.");
        descStep3.setViewportView(descStep3Text);

        GreyLayout.add(descStep3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 350, 50));

        instSeparator1.setForeground(new java.awt.Color(153, 153, 153));
        GreyLayout.add(instSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 880, 10));

        instSeparator2.setForeground(new java.awt.Color(153, 153, 153));
        GreyLayout.add(instSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 880, 10));

        descStep2.setBackground(new java.awt.Color(232, 232, 232));
        descStep2.setBorder(null);
        descStep2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        descStep2Text.setBackground(new java.awt.Color(242, 242, 242));
        descStep2Text.setColumns(20);
        descStep2Text.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        descStep2Text.setForeground(new java.awt.Color(51, 51, 51));
        descStep2Text.setRows(5);
        descStep2Text.setText("Dice 1/2 the apple into small cubes and place \nin the saucepan with the oats. \nBring to a boil and stir until the oats are creamy \nand the apple pieces are tender.\nAbout 4 – 5 minutes. \nAdd a dash more water if necessary.");
        descStep2.setViewportView(descStep2Text);

        GreyLayout.add(descStep2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 370, 90));

        editButt.setBackground(new java.awt.Color(204, 204, 255));
        editButt.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        editButt.setForeground(new java.awt.Color(102, 102, 255));
        editButt.setText("Edit");
        editButt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        editButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtActionPerformed(evt);
            }
        });
        GreyLayout.add(editButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 60, 90, 30));

        saveButt.setBackground(new java.awt.Color(204, 204, 255));
        saveButt.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        saveButt.setForeground(new java.awt.Color(102, 102, 255));
        saveButt.setText("Back");
        saveButt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        saveButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtActionPerformed(evt);
            }
        });
        GreyLayout.add(saveButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 90, 25));

        PurpleLayout.add(GreyLayout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 900, 460));

        Home.setFont(new java.awt.Font("Roboto Slab", 1, 18)); // NOI18N
        Home.setForeground(new java.awt.Color(123, 123, 187));
        Home.setText("Home");
        PurpleLayout.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 5, -1, 38));

        Genius.setFont(new java.awt.Font("Roboto Slab", 1, 18)); // NOI18N
        Genius.setForeground(new java.awt.Color(123, 123, 187));
        Genius.setText("Genius");
        PurpleLayout.add(Genius, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 25, -1, 30));

        HouseIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HomeButton.png"))); // NOI18N
        PurpleLayout.add(HouseIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PurpleLayout, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PurpleLayout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtActionPerformed
        // TODO add your handling code here:
        
        EditRecipe editRecipe = new EditRecipe();
        editRecipe.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_editButtActionPerformed

    private void saveButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtActionPerformed
        // TODO add your handling code here:

        // add code for error if not all text fields/ name have no input "Error saving recipe"


    }//GEN-LAST:event_saveButtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewRecipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewRecipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewRecipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewRecipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewRecipe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Genius;
    private javax.swing.JPanel GreyLayout;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel HouseIcon;
    private javax.swing.JPanel PurpleLayout;
    private javax.swing.JButton addToShoppingList;
    private javax.swing.JScrollPane descStep1;
    private javax.swing.JTextArea descStep1Text;
    private javax.swing.JScrollPane descStep2;
    private javax.swing.JTextArea descStep2Text;
    private javax.swing.JScrollPane descStep3;
    private javax.swing.JTextArea descStep3Text;
    private javax.swing.JScrollPane descStep4;
    private javax.swing.JTextArea descStep4Text;
    private javax.swing.JButton editButt;
    private javax.swing.JLabel image;
    private javax.swing.JPanel ingredientList;
    private javax.swing.JLabel ingredients;
    private javax.swing.JSeparator instSeparator1;
    private javax.swing.JSeparator instSeparator2;
    private javax.swing.JLabel instructions;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JLabel recipeName;
    private javax.swing.JButton saveButt;
    private javax.swing.JSeparator separatorMain;
    private javax.swing.JLabel step1;
    private javax.swing.JLabel step2;
    private javax.swing.JLabel step3;
    private javax.swing.JLabel step4;
    // End of variables declaration//GEN-END:variables
}


